language: dart
sudo: false
dart:
  - stable
  - dev

cache:
  directories:
    - $HOME/.pub-cache
    - .dart_tool/build

script:
  - dartanalyzer --fatal-warnings .
  - pub run test_coverage --no-badge

after_success:
  - bash <(curl -s https://codecov.io/bash)
