name: moronepo
version: 0.1.3
description: >
  A tool to simplify development in a dart multi-package repository.
homepage: https://github.com/meniga/moronepo

environment:
  sdk: ">=2.12.0 <3.0.0"

executables:
  moronepo:

dependencies:
  args: ^2.1.1
  equatable: ^2.0.2
  flutter:
    sdk: flutter
  glob: ^2.0.1
#  json_annotation: ^4.0.1
  logging: ^1.0.1
  meta: ^1.3.0
  pub_semver: ^2.0.0
  pubspec_parse: ^1.0.0
#  path: ^1.6.4
  quiver: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  matcher: ^0.12.5
  mockito: ^5.0.10
  pedantic: ^1.8.0+1
  test: ^1.16.0
