name: moronepo
version: 0.1.3
description: >
  A tool to simplify development in a dart multi-package repository.
homepage: https://github.com/meniga/moronepo

environment:
  sdk: ">=2.5.0 <3.0.0"

executables:
  moronepo:

dependencies:
  args: ^1.5.2
  equatable: ^1.1.1
  flutter:
    sdk: flutter
  glob: ^1.2.0
  json_annotation: ^2.3.0
  logging: ^0.11.4
  meta: ^1.1.7
  pub_semver: ^1.4.4
  pubspec_parse: ^0.1.5
  path: ^1.6.4
  quiver: ^2.0.0

dev_dependencies:
  build_runner: ^1.7.1
  flutter_test:
    sdk: flutter
  json_serializable: ^2.3.0
  matcher: ^0.12.5
  mockito: ^4.1.1
  pedantic: ^1.8.0+1
  test: ^1.6.3
