// Mocks generated by Mockito 5.4.5 from annotations
// in moronepo/test/command/update_sdk_command_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:moronepo/src/flutter_finder/flutter_finder.dart' as _i4;
import 'package:moronepo/src/process_starter/process_starter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProcessOutput_0 extends _i1.SmartFake implements _i2.ProcessOutput {
  _FakeProcessOutput_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProcessStarter].
///
/// See the documentation for Mockito's code generation for more information.
class MockProcessStarter extends _i1.Mock implements _i2.ProcessStarter {
  MockProcessStarter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.ProcessOutput> start(
    String? command,
    List<String>? arguments,
    String? workingDirectory,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#start, [command, arguments, workingDirectory]),
            returnValue: _i3.Future<_i2.ProcessOutput>.value(
              _FakeProcessOutput_0(
                this,
                Invocation.method(#start, [
                  command,
                  arguments,
                  workingDirectory,
                ]),
              ),
            ),
          )
          as _i3.Future<_i2.ProcessOutput>);
}

/// A class which mocks [FlutterFinder].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterFinder extends _i1.Mock implements _i4.FlutterFinder {
  MockFlutterFinder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String findFlutter() =>
      (super.noSuchMethod(
            Invocation.method(#findFlutter, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#findFlutter, []),
            ),
          )
          as String);
}
